name: wubrg_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  supabase_flutter: ^1.10.23


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.0.0
  provider: ^6.0.5
  supabase_flutter: ^1.10.23
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/image1.jpg
  - assets/image2.jpg
  - assets/image3.jpg
  - assets/image4.jpg
  - assets/image5.jpg
  - assets/image6.jpg
  - assets/image7.jpg
  - assets/image8.jpg
  - assets/image9.jpg
  - assets/image10.jpg
  - assets/image11.jpg
  - assets/image12.jpg
  - assets/image13.jpg
  - assets/image14.jpg
  - assets/image15.jpg
  - assets/image16.jpg
  - assets/image17.jpg
  - assets/image18.jpg
  - assets/image19.jpg
  - assets/image20.jpg
  - assets/image21.jpg
  - assets/image22.jpg
  - assets/image23.jpg
  - assets/image24.jpg
  - assets/image25.jpg
  - assets/image26.jpg
  - assets/image27.jpg
  - assets/image28.jpg
  - assets/image29.jpg
  - assets/image30.jpg
  - assets/image31.jpg
  - assets/image32.jpg
  - assets/image33.jpg
  - assets/image34.jpg
  - assets/image35.jpg
  - assets/image36.jpg
  - assets/image37.jpg
  - assets/image38.jpg
  - assets/image39.jpg
  - assets/image40.jpg
  - assets/image41.jpg
  - assets/image42.jpg
  - assets/image43.jpg
  - assets/image44.jpg
  - assets/image45.jpg
  - assets/image46.jpg
  - assets/image47.jpg
  - assets/image48.jpg
  - assets/image49.jpg
  - assets/image50.jpg
  - assets/image51.jpg
  - assets/image52.jpg
  - assets/image53.jpg
  - assets/image54.jpg
  - assets/image55.jpg
  - assets/image56.jpg
  - assets/image57.jpg
  - assets/image58.jpg
  - assets/image59.jpg
  - assets/image60.jpg
  - assets/image61.jpg
  - assets/image62.jpg
  - assets/image63.jpg
  - assets/image64.jpg
  - assets/image65.jpg
  - assets/image66.jpg
  - assets/image67.jpg
  - assets/image68.jpg
  - assets/image69.jpg
  - assets/image70.jpg
  - assets/image71.jpg
  - assets/image72.jpg
  - assets/image73.jpg
  - assets/image74.jpg
  - assets/image75.jpg
  - assets/image76.jpg
  - assets/image77.jpg
  - assets/image78.jpg
  - assets/image79.jpg
  - assets/image80.jpg
  - assets/image81.jpg
  - assets/image82.jpg
  - assets/image83.jpg
  - assets/image84.jpg
  - assets/image85.jpg
  - assets/image86.jpg
  - assets/image87.jpg
  - assets/image88.jpg
  - assets/image89.jpg
  - assets/image90.jpg
  - assets/image91.jpg
  - assets/image92.jpg
  - assets/image93.jpg
  - assets/image94.jpg
  - assets/image95.jpg
  - assets/image96.jpg
  - assets/image97.jpg
  - assets/image98.jpg
  - assets/image99.jpg
  - assets/image100.jpg
  - assets/image101.jpg
  - assets/image102.jpg
  - assets/image103.jpg
  - assets/image104.jpg
  - assets/image105.jpg
  - assets/image106.jpg
  - assets/image107.jpg
  - assets/image108.jpg
  - assets/image109.jpg
  - assets/image110.jpg
  - assets/image111.jpg
  - assets/image112.jpg
  - assets/image113.jpg
  - assets/image114.jpg
  - assets/image115.jpg
  - assets/image116.jpg
  - assets/image117.jpg
  - assets/image118.jpg
  - assets/image119.jpg
  - assets/image120.jpg
  - assets/image121.jpg
  - assets/image122.jpg
  - assets/image123.jpg
  - assets/image124.jpg
  - assets/image125.jpg
  - assets/image126.jpg
  - assets/image127.jpg
  - assets/image128.jpg
  - assets/image129.jpg
  - assets/image130.jpg
  - assets/image131.jpg
  - assets/image132.jpg
  - assets/image133.jpg
  - assets/image134.jpg
  - assets/image135.jpg
  - assets/image136.jpg
  - assets/image137.jpg
  - assets/image138.jpg
  - assets/image139.jpg
  - assets/image140.jpg
  - assets/image141.jpg
  - assets/image142.jpg
  - assets/image143.jpg
  - assets/image144.jpg
  - assets/image145.jpg
  - assets/image146.jpg
  - assets/image147.jpg
  - assets/image148.jpg
  - assets/image149.jpg
  - assets/image150.jpg
  - assets/image151.jpg
  - assets/image152.jpg
  - assets/image153.jpg
  - assets/image154.jpg
  - assets/image155.jpg
  - assets/image156.jpg
  - assets/image157.jpg
  - assets/image158.jpg
  - assets/image159.jpg
  - assets/image160.jpg
  - assets/image161.jpg
  - assets/image162.jpg
  - assets/image163.jpg
  - assets/image164.jpg
  - assets/image165.jpg
  - assets/image166.jpg
  - assets/image167.jpg
  - assets/image168.jpg
  - assets/image169.jpg
  - assets/image170.jpg
  - assets/image171.jpg
  - assets/image172.jpg
  - assets/image173.jpg
  - assets/image174.jpg
  - assets/image175.jpg
  - assets/image176.jpg
  - assets/image177.jpg
  - assets/image178.jpg
  - assets/image179.jpg
  - assets/image180.jpg
  - assets/image181.jpg
  - assets/image182.jpg
  - assets/image183.jpg
  - assets/image184.jpg
  - assets/image185.jpg
  - assets/image186.jpg
  - assets/image187.jpg
  - assets/image188.jpg
  - assets/image189.jpg
  - assets/image190.jpg
  - assets/image191.jpg
  - assets/image192.jpg
  - assets/image193.jpg
  - assets/image194.jpg
  - assets/image195.jpg
  - assets/image196.jpg
  - assets/image197.jpg
  - assets/image198.jpg
  - assets/image199.jpg
  - assets/image200.jpg
  - assets/image201.jpg
  - assets/image202.jpg
  - assets/image203.jpg
  - assets/image204.jpg
  - assets/image205.jpg
  - assets/image206.jpg
  - assets/image207.jpg
  - assets/image208.jpg
  - assets/image209.jpg
  - assets/image210.jpg
  - assets/image211.jpg
  - assets/image212.jpg
  - assets/image213.jpg
  - assets/image214.jpg
  - assets/image215.jpg
  - assets/image216.jpg
  - assets/image217.jpg
  - assets/image218.jpg
  - assets/image219.jpg
  - assets/image220.jpg
  - assets/image221.jpg
  - assets/image222.jpg
  - assets/image223.jpg
  - assets/image224.jpg
  - assets/image225.jpg
  - assets/image226.jpg
  - assets/image227.jpg
  - assets/image228.jpg
  - assets/image229.jpg
  - assets/image230.jpg
  - assets/image231.jpg
  - assets/image232.jpg
  - assets/image233.jpg
  - assets/image234.jpg
  - assets/image235.jpg
  - assets/image236.jpg
  - assets/image237.jpg
  - assets/image238.jpg
  - assets/image239.jpg
  - assets/image240.jpg
  - assets/image241.jpg
  - assets/image242.jpg
  - assets/image243.jpg
  - assets/image244.jpg
  - assets/image245.jpg
  - assets/image246.jpg
  - assets/image247.jpg
  - assets/image248.jpg
  - assets/image249.jpg
  - assets/image250.jpg
  - assets/image251.jpg
  - assets/image252.jpg
  - assets/image253.jpg
  - assets/image254.jpg
  - assets/image255.jpg
  - assets/image256.jpg
  - assets/image257.jpg
  - assets/image258.jpg
  - assets/image259.jpg
  - assets/image260.jpg
  - assets/image261.jpg
  - assets/image262.jpg
  - assets/image263.jpg
  - assets/image264.jpg
  - assets/image265.jpg
  - assets/image266.jpg
  - assets/image267.jpg
  - assets/image268.jpg
  - assets/image269.jpg
  - assets/image270.jpg
  - assets/image271.jpg
  - assets/image272.jpg
  - assets/image273.jpg
  - assets/image274.jpg
  - assets/image275.jpg
  - assets/image276.jpg
  - assets/image277.jpg
  - assets/image278.jpg
  - assets/image279.jpg
  - assets/image280.jpg
  - assets/image281.jpg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
